export const UI_COPY = {
  nav: {
    home: 'Inicio',
    logout: 'Salir'
  },
  common: {
    loading: 'Cargando...',
    notAvailable: 'No disponible',
    noData: 'Sin datos',
    optional: 'Opcional',
    close: 'Cerrar',
    retry: 'Reintentar'
  },
  login: {
    title: 'Toast Club PMV',
    subtitle: 'Inicio de sesión',
    emailLabel: 'Correo',
    passwordLabel: 'Contraseña',
    submit: 'Entrar',
    submitting: 'Iniciando sesión...',
    error: 'No se pudo iniciar sesión. Intenta nuevamente.',
    testAccountsTitle: 'Cuentas de prueba',
    impulsorAccount: 'Impulsador: impulsador@toastclub.com / impulsador123',
    analistaAccount: 'Analista: analista@toastclub.com / analista123'
  },
  impulsor: {
    title: 'Panel del Impulsador',
    subtitle: 'Crea y gestiona sesiones',
    successCreated: 'Sesión creada. Comparte el código con el participante.',
    codeCopied: 'Código copiado al portapapeles.',
    codeCopyError: 'No se pudo copiar el código.',
    startError: 'No se pudo iniciar la sesión',
    continueError: 'No se pudo continuar a la encuesta',
    surveyCompleted: 'Sesión finalizada correctamente',
    currentSessionTitle: 'Sesión actual',
    sessionCode: 'Código de sesión',
    participant: 'Participante',
    state: 'Estado',
    trainingText: 'Texto de entrenamiento',
    noTextSelected: 'Sin texto seleccionado',
    copy: 'Copiar',
    startButton: 'Iniciar sesión',
    waitingAudioTitle: 'Esperando la carga de audio...',
    waitingAudioBody: 'La simulación está en curso. El audio se subirá al finalizar.',
    lastCheck: 'Última revisión',
    audioReceived: 'Audio recibido correctamente',
    continueToSurvey: 'Continuar a la encuesta',
    completedTitle: 'Sesión finalizada',
    newSession: 'Crear nueva sesión'
  },
  analista: {
    title: 'Panel del Analista',
    subtitle: 'Consulta y analiza las sesiones de entrenamiento',
    datasetTitle: 'Dataset de sesiones',
    exportCsv: 'Exportar a CSV',
    loadingDataset: 'Cargando dataset...',
    noDataset: 'No hay datos disponibles.',
    totalSessions: 'Total de sesiones',
    statsTitle: 'Estadísticas del dataset',
    completedSessions: 'Sesiones completadas',
    totalRecordings: 'Total de grabaciones',
    totalSurveys: 'Total de encuestas',
    datasetError: 'No se pudo cargar el dataset',
    exportError: 'No se pudo exportar el dataset'
  },
  sessionForm: {
    title: 'Crear nueva sesión de entrenamiento',
    nameLabel: 'Nombre / Alias *',
    namePlaceholder: 'Ingresa tu nombre o alias',
    ageLabel: 'Edad aproximada',
    agePlaceholder: 'Opcional',
    emailLabel: 'Correo (opcional)',
    emailPlaceholder: 'tu@email.com',
    tagFilters: 'Filtros por etiquetas',
    anyOption: 'Cualquiera',
    searchLabel: 'Buscar por título',
    searchPlaceholder: 'Escribe para buscar...',
    trainingTextLabel: 'Texto de entrenamiento *',
    loadingTexts: 'Cargando textos disponibles...',
    selectTextPlaceholder: '-- Selecciona un texto --',
    noTextsMatch: 'No hay textos que coincidan con los filtros',
    textInfoTitle: 'Información del texto',
    duration: 'Duración',
    topic: 'Tema',
    tone: 'Tono',
    audience: 'Audiencia',
    create: 'Crear sesión',
    creating: 'Creando...',
    loadTextsError: 'No se pudo cargar los textos disponibles',
    createError: 'No se pudo crear la sesión'
  },
  surveyForm: {
    title: 'Encuesta de retroalimentación',
    subtitle: 'Cuéntanos tu experiencia con esta sesión.',
    overallExperience: 'Experiencia general *',
    easeOfUse: 'Facilidad de uso *',
    trainingUsefulness: 'Utilidad del entrenamiento *',
    wouldUseAgain: '¿La usarías de nuevo? *',
    improvements: 'Mejoras sugeridas',
    selectOption: 'Selecciona una opción',
    excellent: 'Excelente',
    good: 'Buena',
    regular: 'Regular',
    bad: 'Mala',
    veryEasy: 'Muy fácil',
    easy: 'Fácil',
    difficult: 'Difícil',
    veryDifficult: 'Muy difícil',
    veryUseful: 'Muy útil',
    useful: 'Útil',
    somewhatUseful: 'Poco útil',
    notUseful: 'Nada útil',
    yes: 'Sí',
    no: 'No',
    maybe: 'Tal vez',
    improvementsPlaceholder: 'Cuéntanos cómo podemos mejorar...',
    submitting: 'Enviando...',
    submit: 'Enviar encuesta',
    submitError: 'No se pudo enviar la encuesta'
  },
  sessionList: {
    noSessions: 'No se encontraron sesiones.',
    sessionCode: 'Código de sesión',
    participant: 'Participante',
    age: 'Edad',
    state: 'Estado',
    createdAt: 'Creada',
    recordings: 'Grabaciones',
    surveys: 'Encuestas',
    details: 'Detalle',
    loading: 'Cargando...',
    moreDetails: 'Más detalles',
    noSurveys: 'Sin encuestas',
    view: 'Ver',
    hide: 'Ocultar',
    participantDetails: 'Detalles del participante',
    name: 'Nombre',
    email: 'Correo',
    trainingText: 'Texto de entrenamiento',
    recordingsTitle: 'Grabaciones',
    noRecordings: 'Sin grabaciones',
    preview: 'Vista previa',
    download: 'Descargar',
    missingRecordingId: 'Falta el id de la grabación',
    surveyResultsTitle: 'Resultados de la encuesta',
    noSurveyResponses: 'No hay respuestas de encuesta.',
    surveyNumber: 'Encuesta',
    submittedAt: 'Enviada',
    close: 'Cerrar',
    surveyLoadError: 'No se pudo cargar el detalle de la encuesta',
    recordingLoadError: 'No se pudo cargar la grabación'
  },
  stateLabels: {
    created: 'Creada',
    ready_to_start: 'Lista para iniciar',
    running: 'En curso',
    audio_uploaded: 'Audio cargado',
    survey_pending: 'Encuesta pendiente',
    completed: 'Completada'
  }
}
